// Regenerate the lightweight tool index used by the homepage and listings:
//   bun scripts/gen-tools-index.ts
import { writeFileSync } from "node:fs";
import { tools } from "../src/data/tools";

const keys = ["slug", "name", "category", "templateGroup", "summary", "featured", "popular", "recent"] as const;
const rows = tools.map((t) => {
  const o: Record<string, unknown> = {};
  for (const k of keys) if (t[k] !== undefined) o[k] = t[k];
  return o;
});
const out = `// AUTO-GENERATED by scripts/gen-tools-index.ts from src/data/tools*.ts — do not edit by hand.
import type { ToolSummary } from "./types";

export const toolIndex: ToolSummary[] = ${JSON.stringify(rows, null, 1)};
`;
writeFileSync(new URL("../src/data/tools-index.ts", import.meta.url), out);
console.log(`wrote ${rows.length} tools`);
