// Regenerate the lightweight tool index used by the homepage and listings:
//   bun scripts/gen-tools-index.ts
import { writeFileSync } from "node:fs";
import { tools } from "../src/data/tools";
import { tutorials } from "../src/data/tutorials";
import { posts } from "../src/data/posts";
import { useCases } from "../src/data/use-cases";

const keys = ["slug", "name", "category", "templateGroup", "summary", "featured", "popular", "recent"] as const;
const rows = tools.map((t) => {
  const o: Record<string, unknown> = {};
  for (const k of keys) if (t[k] !== undefined) o[k] = t[k];
  return o;
});
const out = `// AUTO-GENERATED by scripts/gen-tools-index.ts from src/data/tools*.ts — do not edit by hand.
import type { ToolSummary } from "./types";

export const toolIndex: ToolSummary[] = ${JSON.stringify(rows, null, 1)};
`;
writeFileSync(new URL("../src/data/tools-index.ts", import.meta.url), out);
console.log(`wrote ${rows.length} tools`);

const tut = tutorials.slice(0, 3).map(({ slug, category, h1, description }) => ({ slug, category, h1, description }));
writeFileSync(
  new URL("../src/data/tutorials-featured.ts", import.meta.url),
  `// AUTO-GENERATED by scripts/gen-tools-index.ts — the first three tutorials, for the homepage.\nexport const featuredTutorials = ${JSON.stringify(tut, null, 1)};\n`,
);

const homepagePosts = posts.slice(0, 3).map(({ slug, title, category, excerpt }) => ({ slug, title, category, excerpt }));
const homepageUseCases = [
  ...useCases.slice(0, 6),
  ...useCases.filter(({ slug }) => slug === "ai-for-saas-companies" || slug === "ai-for-real-estate-agents"),
].map(({ slug, name, audience, summary }) => ({ slug, name, audience, summary }));
writeFileSync(
  new URL("../src/data/homepage-content.ts", import.meta.url),
  `// AUTO-GENERATED by scripts/gen-tools-index.ts — lightweight homepage previews.\nexport const homepagePosts = ${JSON.stringify(homepagePosts, null, 1)};\n\nexport const homepageUseCases = ${JSON.stringify(homepageUseCases, null, 1)};\n`,
);
