// AUTO-GENERATED by scripts/gen-tools-index.ts — lightweight homepage previews.
export const homepagePosts = [
 {
  "slug": "how-to-use-ai-for-content-creation",
  "title": "How to Use AI for Content Creation (Without Losing Your Voice)",
  "category": "AI Guides",
  "excerpt": "AI can speed up almost every stage of content creation, but only if you treat it as a drafting partner rather than a replacement for editorial judgment."
 },
 {
  "slug": "how-to-write-a-blog-post-with-ai",
  "title": "How to Write a Blog Post With AI (Step by Step)",
  "category": "AI Writing",
  "excerpt": "Writing a good blog post with AI is less about the generation step and more about the outline, the examples, and the edit that comes after."
 },
 {
  "slug": "how-to-create-ai-videos",
  "title": "How to Create AI Videos: A Realistic Production Guide",
  "category": "AI Video",
  "excerpt": "AI video tools have made short-form video production dramatically faster, but a usable video still comes from a script-first process, not a single prompt."
 }
];

export const homepageUseCases = [
 {
  "slug": "ai-for-marketing",
  "name": "AI for Marketing Teams",
  "audience": "Marketing Teams",
  "summary": "Turn a single campaign brief into ads, emails, and landing pages without the usual back-and-forth."
 },
 {
  "slug": "ai-for-content-creators",
  "name": "AI for Content Creators",
  "audience": "Content Creators",
  "summary": "Turn one video or post idea into scripts, captions, and titles without losing a whole afternoon to it."
 },
 {
  "slug": "ai-for-small-business",
  "name": "AI for Small Business",
  "audience": "Small Business Owners",
  "summary": "Write website copy, ads, and customer emails yourself, without hiring an agency you can't yet afford."
 },
 {
  "slug": "ai-for-entrepreneurs",
  "name": "AI for Entrepreneurs",
  "audience": "Entrepreneurs and Founders",
  "summary": "Turn a new idea into a landing page, pitch copy, and outreach emails fast enough to actually test it."
 },
 {
  "slug": "ai-for-students",
  "name": "AI for Students",
  "audience": "Students",
  "summary": "Summarize readings, brainstorm outlines, and check grammar — as study support, not a way to submit work you didn't write."
 },
 {
  "slug": "ai-for-developers",
  "name": "AI for Developers",
  "audience": "Developers",
  "summary": "Generate boilerplate, draft documentation, and explain technical work without switching out of flow."
 },
 {
  "slug": "ai-for-saas-companies",
  "name": "AI for SaaS Companies",
  "audience": "SaaS Teams",
  "summary": "Connect product marketing, support, sales follow-up and recurring SaaS operations."
 },
 {
  "slug": "ai-for-real-estate-agents",
  "name": "AI for Real Estate Agents",
  "audience": "Real Estate",
  "summary": "Create listings and campaign assets, then organize inquiry and follow-up workflows."
 }
];
