// AUTO-GENERATED by scripts/gen-tools-index.ts from src/data/tools*.ts — do not edit by hand.
import type { ToolSummary } from "./types";

export const toolIndex: ToolSummary[] = [
 {
  "slug": "ai-agent-builder",
  "name": "AI Agent Builder",
  "category": "AI Agents",
  "summary": "Build agents that run real workflows on a schedule or trigger — reading, deciding and acting without you.",
  "featured": true,
  "recent": true
 },
 {
  "slug": "ai-phone-agent",
  "name": "AI Phone Call Agent",
  "category": "AI Agents",
  "summary": "A voice agent that answers and makes real phone calls, books appointments and logs every conversation.",
  "featured": true,
  "recent": true
 },
 {
  "slug": "ai-crm",
  "name": "AI CRM",
  "category": "AI Sales & CRM",
  "summary": "A CRM you talk to: ask about the pipeline, update deals and get reports without touching a spreadsheet.",
  "featured": true,
  "recent": true
 },
 {
  "slug": "ai-social-media-agent",
  "name": "AI Social Media Agent",
  "category": "AI Agents",
  "summary": "An agent that plans, writes, schedules and adjusts a month of social posts across your accounts.",
  "featured": true,
  "recent": true
 },
 {
  "slug": "ai-blogger-agent",
  "name": "AI Blogger Agent",
  "category": "AI Agents",
  "summary": "An agent that researches keywords, writes SEO articles in bulk and publishes them to your blog on a schedule.",
  "featured": true,
  "recent": true
 },
 {
  "slug": "ai-dm-comment-agent",
  "name": "AI DM & Comment Agent",
  "category": "AI Agents",
  "summary": "Auto-reply to Instagram, Facebook and YouTube comments and DMs, capture leads and run campaign promotions.",
  "featured": true,
  "recent": true
 },
 {
  "slug": "ai-deep-research",
  "name": "AI Deep Research",
  "category": "AI Agents",
  "summary": "Multi-source research runs with live web search, compiled into a clear, cited report.",
  "featured": true,
  "recent": true
 },
 {
  "slug": "ugc-factory",
  "name": "UGC Factory",
  "category": "AI Video",
  "summary": "Produce creator-style videos at volume with virtual actors, digital twins, voiceover and lip-synced delivery.",
  "recent": true
 },
 {
  "slug": "viral-clips",
  "name": "Viral Clips",
  "category": "AI Video",
  "summary": "Turn one long video into a set of short vertical clips built for TikTok, Reels and Shorts.",
  "recent": true
 },
 {
  "slug": "ai-video-enhancer",
  "name": "AI Video Enhancer",
  "category": "AI Video",
  "summary": "Upscale and restore video frame by frame for sharper detail and a higher output resolution.",
  "recent": true
 },
 {
  "slug": "ai-council-mode",
  "name": "AI Council Mode",
  "category": "AI Chat",
  "summary": "Ask several AI models the same question at once and compare their answers side by side, or merge them into one.",
  "recent": true
 },
 {
  "slug": "ai-social-media-publisher",
  "name": "AI Social Media Publisher",
  "category": "AI Social Media",
  "summary": "Preview, schedule and publish posts to Facebook, Instagram, X and LinkedIn from one calendar.",
  "recent": true
 },
 {
  "slug": "content-manager",
  "name": "Content Manager",
  "category": "AI Productivity",
  "summary": "One library for everything you upload and generate — images, documents and video, searchable and reusable.",
  "recent": true
 },
 {
  "slug": "ai-rewriter",
  "name": "AI ReWriter",
  "category": "AI Writing",
  "summary": "Rewrite existing text in a different tone, length or reading level while keeping the meaning intact."
 },
 {
  "slug": "brand-voice",
  "name": "Brand Voice",
  "category": "AI Writing",
  "summary": "Define how your brand sounds once, and have every writing tool follow it."
 },
 {
  "slug": "ai-editor",
  "name": "AI Editor",
  "category": "AI Writing",
  "summary": "A long-form document editor with AI help built into the page, for drafting and revising in one place."
 },
 {
  "slug": "ai-image-assistant",
  "name": "AI Image Assistant",
  "category": "AI Image",
  "summary": "Guided prompt help inside image generation — suggestions, refinements and follow-up edits in plain language.",
  "recent": true
 },
 {
  "slug": "ai-realtime-image",
  "name": "AI Realtime Image",
  "category": "AI Image",
  "summary": "Watch the image redraw as you type — change a word and see the result instantly, with no submit and wait.",
  "recent": true
 },
 {
  "slug": "ai-personas",
  "name": "AI Personas & Skills",
  "category": "AI Chat",
  "summary": "Build reusable AI personas with their own role, tone, knowledge and skills, then use them anywhere in the workspace instead of retyping instructions.",
  "recent": true
 },
 {
  "slug": "ai-command-search",
  "name": "AI Command Search",
  "category": "AI Productivity",
  "summary": "One search box that finds the right tool, opens past work and starts the job — type what you want in plain language and press enter.",
  "recent": true
 },
 {
  "slug": "ai-smart-inbox",
  "name": "AI Smart Inbox",
  "category": "AI Sales & CRM",
  "summary": "One inbox for every conversation — website chat, email, social DMs and comments — triaged, tagged and answered by AI.",
  "recent": true
 },
 {
  "slug": "ai-marketing-bot",
  "name": "AI Marketing Bot",
  "category": "AI Marketing",
  "summary": "Broadcast marketing messages to your WhatsApp and Telegram audiences — written by AI, segmented, scheduled and measured.",
  "recent": true
 },
 {
  "slug": "ai-image-editor",
  "name": "AI Image Editor",
  "category": "AI Image",
  "summary": "Edit a photo by describing the change — swap the background, remove objects, extend the frame, fix the light.",
  "recent": true
 },
 {
  "slug": "ai-photoshoot",
  "name": "AI Product Photoshoot",
  "category": "AI Image",
  "summary": "Turn one plain product photo into a full commercial shoot — studio, lifestyle and seasonal scenes.",
  "recent": true
 },
 {
  "slug": "ai-virtual-try-on",
  "name": "AI Fashion Studio",
  "category": "AI Image",
  "summary": "Put a garment on a model without a shoot — same clothes, real fit, any model, any setting.",
  "recent": true
 },
 {
  "slug": "ai-creative-suite",
  "name": "AI Creative Suite",
  "category": "AI Image",
  "summary": "A drag-and-drop design editor with AI image generation — ads, social posts, invitations and banners that all match.",
  "recent": true
 },
 {
  "slug": "ai-video-editor",
  "name": "AI Video Editor",
  "category": "AI Video",
  "summary": "Upload footage and describe the finished cut you want, from pacing and colour to transitions and sound.",
  "recent": true
 },
 {
  "slug": "ai-captions",
  "name": "AI Captions",
  "category": "AI Video",
  "summary": "Turn spoken video into accurately timed, styled captions ready for social platforms and accessible playback.",
  "recent": true
 },
 {
  "slug": "ai-dubbing",
  "name": "AI Dubbing",
  "category": "AI Video",
  "summary": "Translate spoken video into new languages with natural voices, matched timing and a finished localised video.",
  "recent": true
 },
 {
  "slug": "ai-ugc-generator",
  "name": "AI UGC Creator",
  "category": "AI Video",
  "summary": "Create authentic creator-style product videos from a brief, complete with hook, demonstration and call to action.",
  "recent": true
 },
 {
  "slug": "ai-youtube-publisher",
  "name": "AI YouTube & Shorts Publisher",
  "category": "AI Video",
  "summary": "Turn source footage into a packaged YouTube video or Short with edit, title, description, thumbnail direction and schedule.",
  "recent": true
 },
 {
  "slug": "ai-writer",
  "name": "AI Writer",
  "category": "AI Writing",
  "summary": "A flexible writing workspace for drafts, long-form articles, rewrites, and brand-consistent content. Includes templates, the Article Wizard, Smart Editor, and tone controls so every piece stays on-brand.",
  "featured": true,
  "popular": true
 },
 {
  "slug": "ai-chat",
  "name": "AI Chat Pro",
  "category": "AI Chat",
  "summary": "A multi-model chat with personas, reusable skills, smart memory, live web search, file uploads and organised folders — and it hands finished work to the rest of the platform.",
  "featured": true,
  "popular": true
 },
 {
  "slug": "ai-image-generator",
  "name": "AI Image Pro",
  "category": "AI Image",
  "summary": "A full image studio: generate from text, edit with a brush, keep one character or style consistent, swap backgrounds, upscale and export every size you need.",
  "featured": true,
  "popular": true
 },
 {
  "slug": "ai-video-generator",
  "name": "AI Video Pro",
  "category": "AI Video",
  "summary": "Create short videos from text prompts or still images. Includes text-to-video, image-to-video, smooth transitions, and options for captions and voiceover.",
  "featured": true
 },
 {
  "slug": "ai-voice-generator",
  "name": "AI Voiceover & Voice Clone",
  "category": "AI Voice",
  "summary": "Generate natural-sounding voiceovers in 150+ languages and dialects. Clone your own voice or choose from a large library of neural voices, with control over tone, speed, and emotion.",
  "popular": true
 },
 {
  "slug": "ai-text-to-speech",
  "name": "AI Text to Speech",
  "category": "AI Audio",
  "summary": "Convert articles, documents and scripts into clear spoken audio, at length and at speed."
 },
 {
  "slug": "ai-speech-to-text",
  "name": "AI Speech to Text",
  "category": "AI Audio",
  "summary": "Fast, accurate conversion of speech into text, including live dictation and recorded audio."
 },
 {
  "slug": "ai-transcription",
  "name": "AI Transcription",
  "category": "AI Transcription",
  "summary": "Accurately transcribe audio and video files into text with speaker labels and timestamps. Supports multiple languages and common audio formats.",
  "featured": true
 },
 {
  "slug": "ai-avatar-generator",
  "name": "AI Avatar Video Generator",
  "category": "AI Video",
  "summary": "Turn any image into a talking avatar video with realistic lip-sync and natural expressions. Ideal for product explainers, social content, training videos, and personal branding.",
  "featured": true
 },
 {
  "slug": "ai-image-to-video",
  "name": "AI Image to Video",
  "category": "AI Video",
  "summary": "Animate a still image into a short clip with camera movement and controlled motion.",
  "recent": true
 },
 {
  "slug": "ai-code-generator",
  "name": "AI Code Generator",
  "category": "AI Code",
  "summary": "Generate code in multiple languages from natural language descriptions — functions, components, queries and tests, with explanations you can review.",
  "popular": true
 },
 {
  "slug": "ai-vision",
  "name": "AI Vision",
  "category": "AI Vision",
  "summary": "Analyze images, chat with uploaded documents, or analyze any webpage — describe, extract text, compare, and question what you point it at."
 },
 {
  "slug": "ai-document-analyzer",
  "name": "AI Document Analyzer",
  "category": "AI Documents",
  "summary": "Chat with uploaded documents — PDF, Word, CSV — and get summaries, answers with citations, and extracted structured data."
 },
 {
  "slug": "ai-seo-analyzer",
  "name": "AI SEO Analyzer",
  "category": "AI SEO",
  "summary": "Find current keyword and search-question ideas while planning an article, then generate focused metadata for your site and blog posts.",
  "featured": true,
  "popular": true
 },
 {
  "slug": "ai-plagiarism-detector",
  "name": "AI Plagiarism Detector",
  "category": "AI Writing",
  "summary": "Scan any text against online sources to check for duplicated or AI-generated content, with matched source links."
 },
 {
  "slug": "external-chatbot",
  "name": "External Chatbot Builder",
  "category": "AI Chat",
  "summary": "Deploy a branded AI assistant on your website and messaging channels — trained on your content, able to take actions, capture leads and hand hard cases to a human."
 },
 {
  "slug": "ai-presentation-maker",
  "name": "AI Presentation Maker",
  "category": "AI Productivity",
  "summary": "Generate complete, professionally designed slide decks from a topic or brief — layouts and visuals included."
 },
 {
  "slug": "ai-url-to-video",
  "name": "AI URL to Video & Influencer",
  "category": "AI Video",
  "summary": "Paste any product URL and get a complete video ad with voiceover, captions and an avatar — or turn long videos into viral short clips."
 },
 {
  "slug": "sound-studio",
  "name": "Sound Studio",
  "category": "AI Audio",
  "summary": "Merge audio, add background music, adjust voice speed and loudness, and fine-tune voiceovers in one place."
 },
 {
  "slug": "ai-music-generator",
  "name": "AI Music Pro",
  "category": "AI Audio",
  "summary": "Generate original music and background tracks for videos, ads, podcasts and presentations."
 },
 {
  "slug": "ai-chat-bots",
  "name": "AI Chat Bots",
  "category": "AI Chat",
  "summary": "A gallery of creative virtual AI assistants — each trained with the knowledge of industry experts, ready to answer instantly and do its job.",
  "popular": true
 },
 {
  "slug": "article-wizard",
  "name": "Article Wizard",
  "category": "AI Writing",
  "summary": "A guided, step-by-step wizard that walks you from topic to finished long-form article."
 },
 {
  "slug": "blog-ideas-generator",
  "name": "Blog Ideas Generator",
  "category": "AI Templates",
  "templateGroup": "Blog",
  "summary": "Turn a topic or niche into a list of fresh, specific blog post ideas."
 },
 {
  "slug": "blog-outline-generator",
  "name": "Blog Outline Generator",
  "category": "AI Templates",
  "templateGroup": "Blog",
  "summary": "Turn a topic into a clear section-by-section outline before you write a word of prose."
 },
 {
  "slug": "blog-section-writer",
  "name": "Blog Section Writer",
  "category": "AI Templates",
  "templateGroup": "Blog",
  "summary": "Write one section of a blog post at a time, in context with the rest of the piece."
 },
 {
  "slug": "ai-content-detector",
  "name": "AI Content Detector",
  "category": "AI Templates",
  "templateGroup": "Writing",
  "summary": "Scan text and flag sections that read as AI-generated, with a confidence score to guide your edit pass."
 },
 {
  "slug": "web-page-chat",
  "name": "Web Page Chat",
  "category": "AI Chat",
  "summary": "Paste a URL and ask questions about the page's content directly, without reading the whole thing."
 },
 {
  "slug": "chat-with-image",
  "name": "Chat With Image",
  "category": "AI Vision",
  "summary": "Upload an image and ask questions about what's in it, in plain conversation."
 },
 {
  "slug": "realtime-voice-chat",
  "name": "Realtime Voice Chat",
  "category": "AI Voice",
  "summary": "Talk out loud with AI and get spoken replies back, in a live back-and-forth conversation."
 },
 {
  "slug": "testimonial-generator",
  "name": "Testimonial & Review Generator",
  "category": "AI Templates",
  "templateGroup": "Ecommerce",
  "summary": "Turn real customer notes, quotes, and feedback into polished testimonial copy ready for your site."
 },
 {
  "slug": "product-name-generator",
  "name": "Product Name Ideas",
  "category": "AI Templates",
  "templateGroup": "Ecommerce",
  "summary": "Generate a spread of product name options based on your product's features, category, and target audience."
 },
 {
  "slug": "why-choose-this-product",
  "name": "Why Choose This Product",
  "category": "AI Templates",
  "templateGroup": "Ecommerce",
  "summary": "Write a clear, persuasive 'why choose us' section that highlights what actually sets your product apart."
 },
 {
  "slug": "product-review-generator",
  "name": "Product Review Generator",
  "category": "AI Templates",
  "templateGroup": "Ecommerce",
  "summary": "Draft long-form, honest-sounding review articles about a product based on real specs, use, and impressions you provide."
 },
 {
  "slug": "review-responder",
  "name": "Review Responder",
  "category": "AI Templates",
  "templateGroup": "Ecommerce",
  "summary": "Draft on-brand replies to customer reviews — positive, negative, or mixed — in seconds."
 },
 {
  "slug": "instagram-reel-script-generator",
  "name": "Instagram Reel Script Generator",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Turn a topic or product into a scene-by-scene Reel script with hook, beats, and caption."
 },
 {
  "slug": "tiktok-caption-generator",
  "name": "TikTok Video Caption Generator",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Generate TikTok captions with hooks, hashtags, and a tone that matches the video."
 },
 {
  "slug": "facebook-post-generator",
  "name": "Facebook Post Generator",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Generate Facebook posts — announcements, promos, or community updates — in your brand's voice."
 },
 {
  "slug": "facebook-video-script-generator",
  "name": "Facebook Video Script Generator",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Write Facebook video scripts built for feed viewing — hook first, sound-off friendly, clear close."
 },
 {
  "slug": "x-thread-generator",
  "name": "X Thread Generator",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Turn one idea into a structured X (Twitter) thread with a hook tweet and a strong close."
 },
 {
  "slug": "youtube-video-to-blog-post",
  "name": "YouTube Video to Blog Post",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Turn a YouTube video's content or transcript into a structured, readable blog post."
 },
 {
  "slug": "video-idea-generator",
  "name": "Video Idea Generator",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Get a batch of video ideas tailored to your niche, platform, and goal."
 },
 {
  "slug": "video-description-generator",
  "name": "Video Description Generator",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Write SEO-friendly video descriptions with timestamps, keywords, and calls to action."
 },
 {
  "slug": "viral-tweet-generator",
  "name": "Viral Tweet Idea Generator",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Generate tweet ideas built around the patterns that tend to get shared and quoted."
 },
 {
  "slug": "clickbait-title-generator",
  "name": "Clickbait Title Generator",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Generate curiosity-driven titles that earn clicks honestly, without misleading the reader."
 },
 {
  "slug": "ama-post-generator",
  "name": "AMA Post Generator",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Draft an announcement post and starter questions to launch an Ask Me Anything session."
 },
 {
  "slug": "trending-post-generator",
  "name": "Trending Post Generator",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Turn a current trend or topic into a post that fits your niche without forcing it."
 },
 {
  "slug": "viral-ideas-generator",
  "name": "Viral Ideas Generator",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Generate content ideas across formats built around what tends to get shared and discussed."
 },
 {
  "slug": "storytelling-generator",
  "name": "Storytelling Generator",
  "category": "AI Templates",
  "templateGroup": "Social",
  "summary": "Turn a plain fact or experience into a short story-style post with a real narrative arc."
 },
 {
  "slug": "sitemap-generator",
  "name": "Website Sitemap Generator",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Turn a business description into a full website structure of pages, sections, and navigation."
 },
 {
  "slug": "tagline-generator",
  "name": "Tagline Generator",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Generate short, memorable taglines that sum up your brand in one line."
 },
 {
  "slug": "ux-ideas-generator",
  "name": "UX Ideas Generator",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Get concrete UX improvement ideas for a page, flow, or feature you describe."
 },
 {
  "slug": "design-ideas-generator",
  "name": "Design Ideas Generator",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Brainstorm visual design directions for a page, brand, or campaign from a short brief."
 },
 {
  "slug": "services-page-generator",
  "name": "Services Page Generator",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Turn a list of services into a clear, structured services page with descriptions and calls to action."
 },
 {
  "slug": "features-page-generator",
  "name": "Features Page Generator",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Turn a feature list into a structured features page with clear explanations and benefits."
 },
 {
  "slug": "keyword-generator",
  "name": "Keyword Generator",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Generate relevant keyword ideas for a topic, product, or page to guide your SEO and content plans."
 },
 {
  "slug": "keyword-extractor",
  "name": "Keyword Extractor",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Pull the key terms and phrases out of any existing text — a page, article, or document."
 },
 {
  "slug": "website-testimonials-generator",
  "name": "Website Testimonials Generator",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Turn real customer feedback into polished, on-site testimonial blocks — never fabricated quotes."
 },
 {
  "slug": "landing-page-copy-generator",
  "name": "Landing Page Copy Generator",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Generate full landing page copy — headline, subhead, sections, and CTA — from a short product brief."
 },
 {
  "slug": "website-copy-generator",
  "name": "Website Copy Generator",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Generate copy for any website page — home, about, or product — from a short description of your business."
 },
 {
  "slug": "call-to-action-generator",
  "name": "Call to Action Generator",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Generate strong call-to-action lines for buttons, emails, and landing pages that match your goal."
 },
 {
  "slug": "privacy-policy-generator",
  "name": "Privacy Policy Generator",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Generate a starting-draft privacy policy from a description of your business and data practices — not legal advice."
 },
 {
  "slug": "terms-and-conditions-generator",
  "name": "Terms and Conditions Generator",
  "category": "AI Templates",
  "templateGroup": "Website",
  "summary": "Generate a starting-draft terms and conditions page from your business details — not legal advice."
 },
 {
  "slug": "tv-ad-script-generator",
  "name": "TV Ad Script Generator",
  "category": "AI Templates",
  "templateGroup": "Advertising",
  "summary": "Turn a product idea into a broadcast-ready TV commercial script with scenes, dialogue, and voiceover cues."
 },
 {
  "slug": "youtube-ads-generator",
  "name": "YouTube Ads Generator",
  "category": "AI Templates",
  "templateGroup": "Advertising",
  "summary": "Generate skippable and non-skippable YouTube ad scripts built around the first five seconds that matter most."
 },
 {
  "slug": "ad-script-generator",
  "name": "Ad Script Generator",
  "category": "AI Templates",
  "templateGroup": "Advertising",
  "summary": "Generate ad scripts for any channel — video, audio, or social — from a single product brief."
 },
 {
  "slug": "advertising-ideas-generator",
  "name": "Advertising Ideas Generator",
  "category": "AI Templates",
  "templateGroup": "Advertising",
  "summary": "Brainstorm campaign concepts and creative angles for any product before you write a single line of copy."
 },
 {
  "slug": "app-notification-generator",
  "name": "App & SMS Notification Generator",
  "category": "AI Templates",
  "templateGroup": "Advertising",
  "summary": "Write short push notifications and SMS messages that get opened, not swiped away."
 },
 {
  "slug": "aida-framework-generator",
  "name": "AIDA Framework Generator",
  "category": "AI Templates",
  "templateGroup": "Advertising",
  "summary": "Generate marketing copy structured around Attention, Interest, Desire, and Action for any product or offer."
 },
 {
  "slug": "pas-framework-generator",
  "name": "PAS Framework Generator",
  "category": "AI Templates",
  "templateGroup": "Advertising",
  "summary": "Write copy structured around Problem, Agitation, Solution to make an offer feel like the obvious next step."
 },
 {
  "slug": "marketing-plan-generator",
  "name": "Marketing Plan Generator",
  "category": "AI Templates",
  "templateGroup": "Advertising",
  "summary": "Turn a business goal into a structured marketing plan with channels, timeline, and key messages."
 },
 {
  "slug": "sales-pitch-generator",
  "name": "Sales Pitch Generator",
  "category": "AI Templates",
  "templateGroup": "Advertising",
  "summary": "Turn a product and audience into a tight sales pitch for calls, decks, or emails."
 },
 {
  "slug": "job-description-generator",
  "name": "Job Description Generator",
  "category": "AI Templates",
  "templateGroup": "Business",
  "summary": "Turn a role and a few requirements into a clear, complete job posting."
 },
 {
  "slug": "ai-resume-builder",
  "name": "AI Resume Builder",
  "category": "AI Templates",
  "templateGroup": "Business",
  "summary": "Turn your work history into a polished, well-structured resume."
 },
 {
  "slug": "linkedin-profile-generator",
  "name": "LinkedIn Profile Generator",
  "category": "AI Templates",
  "templateGroup": "Business",
  "summary": "Turn your career background into a strong LinkedIn headline, about section, and experience bullets."
 },
 {
  "slug": "linkedin-post-generator",
  "name": "LinkedIn Post Generator",
  "category": "AI Templates",
  "templateGroup": "Business",
  "summary": "Turn an idea, milestone, or insight into a LinkedIn post that reads like it came from a person, not a brand account."
 },
 {
  "slug": "startup-ideas-generator",
  "name": "Startup Ideas Generator",
  "category": "AI Templates",
  "templateGroup": "Business",
  "summary": "Turn an industry, skill set, or problem area into a list of concrete startup ideas worth exploring."
 },
 {
  "slug": "business-strategy-generator",
  "name": "Business Strategy Generator",
  "category": "AI Templates",
  "templateGroup": "Business",
  "summary": "Turn a business goal and current situation into a structured strategy outline."
 },
 {
  "slug": "personal-bio-generator",
  "name": "Personal Bio Generator",
  "category": "AI Templates",
  "templateGroup": "Business",
  "summary": "Turn your background and achievements into a polished bio for any platform."
 },
 {
  "slug": "cost-benefit-analysis-generator",
  "name": "Cost Benefit Analysis Generator",
  "category": "AI Templates",
  "templateGroup": "Business",
  "summary": "Turn a decision into a structured cost-benefit breakdown you can actually use."
 },
 {
  "slug": "brainstorming-generator",
  "name": "Brainstorming Generator",
  "category": "AI Templates",
  "templateGroup": "Business",
  "summary": "Turn a prompt or problem into a wide list of ideas to react to and refine."
 },
 {
  "slug": "cover-letter-generator",
  "name": "Cover Letter Generator",
  "category": "AI Templates",
  "templateGroup": "Academic",
  "summary": "Turn a job posting and your background into a tailored, ready-to-edit cover letter."
 },
 {
  "slug": "application-letter-generator",
  "name": "Application Letter Generator",
  "category": "AI Templates",
  "templateGroup": "Academic",
  "summary": "Draft formal application letters for jobs, programs, or memberships from a short brief."
 },
 {
  "slug": "math-question-solver",
  "name": "Math Question Solver",
  "category": "AI Templates",
  "templateGroup": "Academic",
  "summary": "Get a math problem solved step by step, so you understand the method — not just the answer."
 },
 {
  "slug": "bullet-point-answer-generator",
  "name": "Bullet Point Answer Generator",
  "category": "AI Templates",
  "templateGroup": "Academic",
  "summary": "Turn a study question into clear, organized bullet points you can review and learn from."
 },
 {
  "slug": "thesis-statement-generator",
  "name": "Thesis Statement Generator",
  "category": "AI Templates",
  "templateGroup": "Academic",
  "summary": "Turn an essay topic into a focused, arguable thesis statement to build your paper around."
 },
 {
  "slug": "ai-proofreader",
  "name": "AI Proofreader",
  "category": "AI Templates",
  "templateGroup": "Academic",
  "summary": "Catch grammar, spelling, and punctuation errors before you hit send or submit."
 },
 {
  "slug": "ai-rephraser",
  "name": "AI Rephraser",
  "category": "AI Templates",
  "templateGroup": "Academic",
  "summary": "Rephrase sentences or paragraphs to improve clarity, tone, or flow while keeping the original meaning."
 },
 {
  "slug": "content-improver",
  "name": "Content Improver",
  "category": "AI Templates",
  "templateGroup": "Academic",
  "summary": "Get targeted suggestions to sharpen weak sentences, tighten structure, and strengthen a draft overall."
 },
 {
  "slug": "career-advice-generator",
  "name": "Career Advice Generator",
  "category": "AI Templates",
  "templateGroup": "Academic",
  "summary": "Get tailored career guidance on next steps, skill gaps, or a career change based on your situation."
 },
 {
  "slug": "welcome-email-generator",
  "name": "Welcome Email Generator",
  "category": "AI Templates",
  "templateGroup": "Communications",
  "summary": "Write a warm, on-brand welcome email for new subscribers or customers in seconds."
 },
 {
  "slug": "invitation-email-generator",
  "name": "Invitation Email Generator",
  "category": "AI Templates",
  "templateGroup": "Communications",
  "summary": "Draft clear, inviting event or meeting invitation emails in a fraction of the time."
 },
 {
  "slug": "reply-email-generator",
  "name": "Reply Email Generator",
  "category": "AI Templates",
  "templateGroup": "Communications",
  "summary": "Turn an incoming email into a clear, appropriately toned reply in seconds."
 },
 {
  "slug": "apology-email-generator",
  "name": "Apology Email Generator",
  "category": "AI Templates",
  "templateGroup": "Communications",
  "summary": "Write a sincere, well-structured apology email for mistakes, delays, or service issues."
 },
 {
  "slug": "bug-fix-assistant",
  "name": "AI Bug Fix Assistant",
  "category": "AI Templates",
  "templateGroup": "Communications",
  "summary": "Paste broken code and an error message to get a diagnosis and a working fix."
 },
 {
  "slug": "explain-code",
  "name": "Explain Code",
  "category": "AI Templates",
  "templateGroup": "Communications",
  "summary": "Paste any code snippet and get a plain-language explanation of what it does and why."
 },
 {
  "slug": "teach-code",
  "name": "Teach Me to Code",
  "category": "AI Templates",
  "templateGroup": "Communications",
  "summary": "Get a beginner-friendly lesson on any coding concept, tailored to your current level."
 },
 {
  "slug": "changelog-generator",
  "name": "Changelog Generator",
  "category": "AI Templates",
  "templateGroup": "Communications",
  "summary": "Turn a list of commits or updates into a clear, readable changelog for your users."
 },
 {
  "slug": "ai-translator",
  "name": "AI Translator",
  "category": "AI Templates",
  "templateGroup": "Communications",
  "summary": "Translate text between languages while keeping tone, nuance, and meaning intact."
 },
 {
  "slug": "synonyms-generator",
  "name": "Synonyms Generator",
  "category": "AI Templates",
  "templateGroup": "Communications",
  "summary": "Find the right word fast with context-aware synonym suggestions."
 },
 {
  "slug": "learn-new-words",
  "name": "Learn New Words",
  "category": "AI Templates",
  "templateGroup": "Communications",
  "summary": "Build vocabulary with clear definitions, example sentences, and memory-friendly context."
 },
 {
  "slug": "social-media-reply-generator",
  "name": "Social Media Reply Generator",
  "category": "AI Templates",
  "templateGroup": "Communications",
  "summary": "Draft quick, on-brand replies to comments and mentions across your social channels."
 },
 {
  "slug": "support-ticket-reply-generator",
  "name": "Support Ticket Reply Generator",
  "category": "AI Templates",
  "templateGroup": "Communications",
  "summary": "Draft clear, helpful support ticket replies from the customer's message and your resolution."
 },
 {
  "slug": "song-lyrics-generator",
  "name": "Song Lyrics Generator",
  "category": "AI Templates",
  "templateGroup": "Lifestyle",
  "summary": "Turn a theme, genre, and mood into a structured set of song lyrics with verses, chorus, and bridge."
 },
 {
  "slug": "joke-generator",
  "name": "Joke Generator",
  "category": "AI Templates",
  "templateGroup": "Lifestyle",
  "summary": "Generate jokes, puns, and one-liners on any topic for speeches, captions, or just a laugh."
 },
 {
  "slug": "event-planner",
  "name": "AI Event Planner",
  "category": "AI Templates",
  "templateGroup": "Lifestyle",
  "summary": "Turn an event idea into a timeline, checklist, and budget outline in minutes."
 },
 {
  "slug": "travel-planner",
  "name": "AI Travel Planner",
  "category": "AI Templates",
  "templateGroup": "Lifestyle",
  "summary": "Turn a destination, dates, and budget into a day-by-day itinerary."
 },
 {
  "slug": "gift-ideas-generator",
  "name": "Gift Ideas Generator",
  "category": "AI Templates",
  "templateGroup": "Lifestyle",
  "summary": "Turn a recipient's interests, budget, and occasion into a shortlist of specific gift ideas."
 },
 {
  "slug": "workout-plan-generator",
  "name": "Workout Plan Generator",
  "category": "AI Templates",
  "templateGroup": "Lifestyle",
  "summary": "Generate a structured weekly workout plan based on your goals, experience, and available equipment."
 },
 {
  "slug": "meal-plan-generator",
  "name": "Meal Plan Generator",
  "category": "AI Templates",
  "templateGroup": "Lifestyle",
  "summary": "Generate a weekly meal plan based on your goals, preferences, and dietary style."
 },
 {
  "slug": "ebook-generator",
  "name": "eBook Generator",
  "category": "AI Templates",
  "templateGroup": "Writing",
  "summary": "Turn a topic and outline into a full multi-chapter eBook draft, ready to design and publish."
 },
 {
  "slug": "book-ideas-generator",
  "name": "Book Ideas Generator",
  "category": "AI Templates",
  "templateGroup": "Writing",
  "summary": "Get a batch of book concepts — premise, angle, and audience — from a genre or theme."
 },
 {
  "slug": "explain-to-a-child",
  "name": "Explain to a Child",
  "category": "AI Templates",
  "templateGroup": "Writing",
  "summary": "Turn a complex topic into a simple explanation a child could follow, using plain words and relatable comparisons."
 },
 {
  "slug": "journalist-news-generator",
  "name": "News From a Journalist's View",
  "category": "AI Templates",
  "templateGroup": "Writing",
  "summary": "Draft a news-style article structure from your notes — a writing aid, not a fact-generation tool."
 },
 {
  "slug": "rss-feed-generator",
  "name": "Generate From RSS Feed",
  "category": "AI Writing",
  "summary": "Turn items from an RSS feed into fresh written content — summaries, roundups, or posts — ready to review."
 },
 {
  "slug": "undetectable-ai-humanizer",
  "name": "Undetectable AI Humanizer",
  "category": "AI Templates",
  "templateGroup": "Writing",
  "summary": "Smooth out AI-drafted text so it reads naturally, in your own voice, instead of sounding stiff or templated."
 },
 {
  "slug": "pros-and-cons-generator",
  "name": "Pros and Cons Generator",
  "category": "AI Templates",
  "templateGroup": "Writing",
  "summary": "Lay out the real advantages and disadvantages of any decision, side by side, before you commit."
 },
 {
  "slug": "real-estate-listing-generator",
  "name": "Real Estate Listing Generator",
  "category": "AI Templates",
  "templateGroup": "Writing",
  "summary": "Turn property details into a compelling, ready-to-post real estate listing description."
 },
 {
  "slug": "prompt-generator",
  "name": "AI Prompt Generator",
  "category": "AI Templates",
  "templateGroup": "Writing",
  "summary": "Turn a rough idea into a clear, detailed prompt that gets better results from any AI tool."
 },
 {
  "slug": "ai-voice-isolator",
  "name": "AI Voice Isolator",
  "category": "AI Audio",
  "summary": "Strip background noise and music from a recording, leaving clean, clear speech behind."
 },
 {
  "slug": "ai-video-to-video",
  "name": "AI Video to Video",
  "category": "AI Templates",
  "templateGroup": "Writing",
  "summary": "Restyle or enhance an existing video clip into a new finished version, based on your instructions."
 }
];
